"""add owner_id to objects

Revision ID: c1fdc6c1bce2
Revises: c99f9c7e897e
Create Date: 2026-04-29 21:02:03.069223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1fdc6c1bce2'
down_revision: Union[str, Sequence[str], None] = 'c99f9c7e897e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('owner_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'owner_id')
    # ### end Alembic commands ###
